[project]
name = "call-center-coach"
version = "0.1.0"
description = "A demo about how AI can be a Sales Coach"
author = "Hassen Taidirt"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
